apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: stdlayout
  description: >-
    prudential standard layout encapsulated in the asyc spec to be rendered in
    backstage
  annotations:
    backstage.io/techdocs-ref: dir:./
  tags:
    - aws
  links:
    - url: 'https://github.com/asyncapi/asyncapi/blob/master/examples/1.2.0/std.yml'
      title: Source Code
      icon: code
spec:
  type: asyncapi
  lifecycle: production
  owner: team-c
  definition: 
    $text: https://raw.githubusercontent.com/AravindRTW/HoundAPI/main/HoundAPI/apidocs/prudentialasyncapispecfile.yaml
