
name: Translate Stoplight UPdates to Backstage Catalog

on:
  push:
    paths:
      - '**.json'
jobs:
  job1:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
  - name: Modifiy the specific files using scripts
    run: |
      --- shell scripts or command lines to execute ---
 
      
  - name: Commit and push changes
    run: |
      git config --global user.name "AravindRTW"
      git config --global user.email "aravind.rajendran@thoughtworks.com"

      git add -A
      git commit -m "commit message"
      git push
